/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.roguelike;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import com.example.roguelike.Player; // Added for clarity

public class Main {

    private Player player;

    public Main() {
        this.player = new Player(10, 10);
        // You can print player's initial position here for verification if needed
        // System.out.println("Player initialized at: " + player.getX() + ", " + player.getY());
    }

    public void startGameLoop() {
        while (true) {
            System.out.println("Player position: X=" + player.getX() + ", Y=" + player.getY());
            try {
                Thread.sleep(1000); // 1 second delay
            } catch (InterruptedException e) {
                System.err.println("Game loop interrupted");
                Thread.currentThread().interrupt(); // Restore interrupted status
                break; // Exit loop if interrupted
            }
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Roguelike Game");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(800, 600);
                frame.setVisible(true);
            }
        });

        // Start the game loop in a new thread
        Thread gameLoopThread = new Thread(new Runnable() {
            public void run() {
                new Main().startGameLoop();
            }
        });
        gameLoopThread.start();
    }
}
