/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.roguelike;

import javax.swing.SwingUtilities;

/**
 * Main class to initialize and start the Roguelike game.
 */
public class Main {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            // Create the main game object
            Game game = new Game();

            // Create and attach the input handler
            InputHandler inputHandler = new InputHandler(game.getPlayer(), game.getTileMap()); // Use getTileMap()
            inputHandler.attach(game.getFrame()); // Attach to the JFrame from Game

            // Start the game loop in a new thread
            new Thread(game::startGameLoop).start();
        });
    }
}
